# Claire de Binare - Base Infrastructure
# Core Services (Redis, Postgres, Prometheus, Grafana)
# No Port-Bindings (internal only)

# Issue #232: Deterministic project naming via STACK_NAME
name: ${STACK_NAME:-cdb}

services:
  cdb_redis:
    image: redis:7-alpine
    container_name: cdb_redis
    restart: unless-stopped
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    command: /bin/sh -c "redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --requirepass $$REDIS_PASSWORD"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a $$REDIS_PASSWORD ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - cdb_network

  cdb_postgres:
    image: postgres:15-alpine
    container_name: cdb_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: claire_de_binare
      POSTGRES_USER: ${POSTGRES_USER:-claire_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../infrastructure/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ../../infrastructure/database/migrations/002_orders_price_nullable.sql:/docker-entrypoint-initdb.d/02-migration-002.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-claire_user} -d claire_de_binare"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - cdb_network

  cdb_prometheus:
    image: prom/prometheus:v2.51.0
    container_name: cdb_prometheus
    restart: unless-stopped
    volumes:
      - ../../infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/-/healthy > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cdb_network

  cdb_grafana:
    image: grafana/grafana:11.4.0
    container_name: cdb_grafana
    restart: unless-stopped
    env_file: .env
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../infrastructure/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ../../infrastructure/monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../../infrastructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - cdb_prometheus
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cdb_network

volumes:
  redis_data:
  postgres_data:
  prom_data:
  grafana_data:

networks:
  cdb_network:
    driver: bridge
