# Claire de Binare - Dev Overrides
# Port-Bindings, Debug-Volumes, Relaxed Security
# Network Isolation: All ports bound to localhost (127.0.0.1) only
#
# SECRETS ARCHITECTURE:
# - All secrets read from /run/secrets/ files
# - Entrypoint exports secrets as env vars for Python apps
# - Not visible in `docker inspect` output

services:
  # Override Base Services with Port-Bindings
  cdb_redis:
    ports:
      - "127.0.0.1:6379:6379"

  cdb_postgres:
    ports:
      - "127.0.0.1:5432:5432"

  cdb_prometheus:
    ports:
      - "127.0.0.1:19090:9090"

  cdb_grafana:
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}

  # Application Services (Dev-Only)
  # All use entrypoint pattern to read secrets from /run/secrets/

  cdb_ws:
    build:
      context: ../..
      dockerfile: services/ws/Dockerfile
    container_name: cdb_ws
    restart: unless-stopped
    secrets:
      - redis_password
      - postgres_password
    environment:
      ENV: "development"
      LOG_LEVEL: "DEBUG"
      REDIS_HOST: cdb_redis
      POSTGRES_HOST: cdb_postgres
      POSTGRES_USER: ${POSTGRES_USER:-claire_user}
      WS_SOURCE: mexc_pb
      MEXC_SYMBOL: BTCUSDT
      MEXC_INTERVAL: 100ms
    entrypoint: ["sh", "-c", "export REDIS_PASSWORD=$(cat /run/secrets/redis_password) && export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password) && exec python -u service.py"]
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ../../logs:/app/logs
    depends_on:
      - cdb_redis
      - cdb_postgres
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - cdb_network

  cdb_signal:
    build:
      context: ../..
      dockerfile: services/signal/Dockerfile
    container_name: cdb_signal
    restart: unless-stopped
    secrets:
      - redis_password
      - postgres_password
    environment:
      ENV: "development"
      LOG_LEVEL: "DEBUG"
      REDIS_HOST: cdb_redis
      POSTGRES_HOST: cdb_postgres
      POSTGRES_USER: ${POSTGRES_USER:-claire_user}
      SIGNAL_STRATEGY_ID: ${SIGNAL_STRATEGY_ID:-paper}
      SIGNAL_PORT: "8005"
      SIGNAL_THRESHOLD_PCT: "0.005"  # Issue #345: Evidence-based: 100ms trades max ~0.014%, most <0.01%
      SIGNAL_MIN_VOLUME: "0"  # DISABLED: Raw trades use 'qty' field, not 'volume' (TODO: fix field mapping)
    entrypoint: ["sh", "-c", "export REDIS_PASSWORD=$(cat /run/secrets/redis_password) && export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password) && exec python -m services.signal.service"]
    ports:
      - "127.0.0.1:8005:8005"
    volumes:
      - ../../logs:/app/logs
    depends_on:
      - cdb_redis
      - cdb_postgres
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8005/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - cdb_network

  cdb_risk:
    build:
      context: ../..
      dockerfile: services/risk/Dockerfile
    container_name: cdb_risk
    restart: unless-stopped
    secrets:
      - redis_password
      - postgres_password
    environment:
      ENV: "development"
      LOG_LEVEL: "DEBUG"
      REDIS_HOST: cdb_redis
      POSTGRES_HOST: cdb_postgres
      POSTGRES_USER: ${POSTGRES_USER:-claire_user}
    entrypoint: ["sh", "-c", "export REDIS_PASSWORD=$(cat /run/secrets/redis_password) && export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password) && exec python -m services.risk.service"]
    ports:
      - "127.0.0.1:8002:8002"
    volumes:
      - ../../logs:/app/logs
    depends_on:
      - cdb_redis
      - cdb_postgres
    networks:
      - cdb_network

  cdb_execution:
    build:
      context: ../..
      dockerfile: services/execution/Dockerfile
    container_name: cdb_execution
    restart: unless-stopped
    secrets:
      - redis_password
      - postgres_password
      - mexc_api_key
      - mexc_api_secret
    environment:
      ENV: "development"
      LOG_LEVEL: "DEBUG"
      REDIS_HOST: cdb_redis
      POSTGRES_HOST: cdb_postgres
      POSTGRES_USER: ${POSTGRES_USER:-claire_user}
    entrypoint: ["sh", "-c", "export REDIS_PASSWORD=$(cat /run/secrets/redis_password) && export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password) && exec python -u service.py"]
    ports:
      - "127.0.0.1:8003:8003"
    volumes:
      - ../../logs:/app/logs
    depends_on:
      - cdb_redis
      - cdb_postgres
    networks:
      - cdb_network

  cdb_db_writer:
    build:
      context: ../..
      dockerfile: services/db_writer/Dockerfile
    container_name: cdb_db_writer
    restart: unless-stopped
    secrets:
      - redis_password
      - postgres_password
    environment:
      ENV: "development"
      LOG_LEVEL: "DEBUG"
      REDIS_HOST: cdb_redis
      POSTGRES_HOST: cdb_postgres
      POSTGRES_USER: ${POSTGRES_USER:-claire_user}
    entrypoint: ["sh", "-c", "export REDIS_PASSWORD=$(cat /run/secrets/redis_password) && export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password) && exec python -u db_writer.py"]
    healthcheck:
      test: ["CMD-SHELL", "kill -0 1 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      - cdb_redis
      - cdb_postgres
    networks:
      - cdb_network

  # Paper Trading Runner Service
  cdb_paper_runner:
    build:
      context: ../..
      dockerfile: tools/paper_trading/Dockerfile
    container_name: cdb_paper_runner
    restart: unless-stopped
    secrets:
      - redis_password
      - postgres_password
    environment:
      ENV: "development"
      LOG_LEVEL: "DEBUG"
      REDIS_HOST: cdb_redis
      POSTGRES_HOST: cdb_postgres
      POSTGRES_USER: ${POSTGRES_USER:-claire_user}
      PAPER_TRADING_DURATION_DAYS: ${PAPER_TRADING_DURATION_DAYS:-14}
    entrypoint: ["sh", "-c", "export REDIS_PASSWORD=$(cat /run/secrets/redis_password) && export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password) && exec python tools/paper_trading/service.py"]
    ports:
      - "127.0.0.1:8004:8004"
    volumes:
      - ../../logs:/app/logs
      - ../../tools/paper_trading:/app/tools/paper_trading:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      cdb_redis:
        condition: service_healthy
      cdb_postgres:
        condition: service_healthy
    networks:
      - cdb_network
