# Rollback Overlay
# Pins services to specific tagged images for rollback capability
# Usage: Used internally by stack_rollback.ps1
# Set ROLLBACK_TAG environment variable before using
#
# Status (2025-12-24):
# - Active services: cdb_core, cdb_risk, cdb_execution, cdb_db_writer
# - Future services: cdb_allocation, cdb_regime, cdb_market (Dockerfiles exist, not active)
# - Planned services: cdb_ws, cdb_paper_runner (not yet implemented)

services:
  # === ACTIVE APPLICATION SERVICES ===

  cdb_core:
    image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_core:${ROLLBACK_TAG:-latest}
    build: null

  cdb_risk:
    image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_risk:${ROLLBACK_TAG:-latest}
    build: null

  cdb_execution:
    image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_execution:${ROLLBACK_TAG:-latest}
    build: null

  cdb_db_writer:
    image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_db_writer:${ROLLBACK_TAG:-latest}
    build: null

  # === FUTURE SERVICES (Dockerfiles exist, awaiting configuration) ===

  cdb_allocation:
    image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_allocation:${ROLLBACK_TAG:-latest}
    build: null

  cdb_regime:
    image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_regime:${ROLLBACK_TAG:-latest}
    build: null

  cdb_market:
    image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_market:${ROLLBACK_TAG:-latest}
    build: null

  # === PLANNED SERVICES (Not yet implemented) ===

  # cdb_paper_runner:
  #   image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_paper_runner:${ROLLBACK_TAG:-latest}
  #   build: null

  # cdb_ws:
  #   image: ${COMPOSE_PROJECT_NAME:-claire_de_binare}_cdb_ws:${ROLLBACK_TAG:-latest}
  #   build: null
