
name: Issue Governance (Milestones)

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write
  contents: read

jobs:
  milestone-autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Set milestone from Phase in title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title || "";
            // Match "... - Phase <n> - ..."
            const m = title.match(/\bPhase\s+(\d+)\b/i);
            let phase = m ? parseInt(m[1], 10) : null;

            // Optional: "Final" keyword -> M9
            const isFinal = /\bfinal\b/i.test(title);

            const phaseToMilestonePrefix = {
              0: "M1",
              1: "M2",
              2: "M3",
              3: "M4",
              4: "M7",
              5: "M8",
              6: "M6",
            };

            let targetPrefix = null;
            if (isFinal) targetPrefix = "M9";
            else if (phase !== null && phaseToMilestonePrefix[phase] !== undefined) {
              targetPrefix = phaseToMilestonePrefix[phase];
            } else {
              core.info("No phase detected (or unmapped). Skipping.");
              return;
            }

            const { owner, repo } = context.repo;
            const milestones = await github.paginate(github.rest.issues.listMilestones, {
              owner, repo, state: "open", per_page: 100,
            });

            const target = milestones.find(ms => (ms.title || "").startsWith(targetPrefix));
            if (!target) {
              core.warning(`Target milestone starting with "${targetPrefix}" not found. Skipping.`);
              return;
            }

            const issue = context.payload.issue;
            const current = issue.milestone ? issue.milestone.number : null;

            if (current === target.number) {
              core.info(`Milestone already set to ${target.title}.`);
              return;
            }

            await github.rest.issues.update({
              owner, repo,
              issue_number: issue.number,
              milestone: target.number,
            });

            core.info(`Milestone set to ${target.title} for issue #${issue.number}.`);
