"""Stable reason and classification codes for CDB worktree governance."""

from __future__ import annotations

# Policy / create (Windows applicable)
WORKTREE_PATH_ALLOWED = "WORKTREE_PATH_ALLOWED"
WORKTREE_POLICY_NOT_APPLICABLE = "WORKTREE_POLICY_NOT_APPLICABLE"
WORKTREE_ON_C_DRIVE = "WORKTREE_ON_C_DRIVE"
WORKTREE_ON_D_DRIVE = "WORKTREE_ON_D_DRIVE"
WORKTREE_OUTSIDE_CANONICAL_ROOT = "WORKTREE_OUTSIDE_CANONICAL_ROOT"
WORKTREE_ROOT_UNAVAILABLE = "WORKTREE_ROOT_UNAVAILABLE"
HOLD_WORKTREE_ROOT_UNAVAILABLE = "HOLD_WORKTREE_ROOT_UNAVAILABLE"
WORKTREE_ROOT_NOT_WRITABLE = "WORKTREE_ROOT_NOT_WRITABLE"
HOLD_WORKTREE_ROOT_NOT_WRITABLE = "HOLD_WORKTREE_ROOT_NOT_WRITABLE"
HOLD_WORKTREE_PATH_OUTSIDE_ALLOWED_ROOT = "HOLD_WORKTREE_PATH_OUTSIDE_ALLOWED_ROOT"
WORKTREE_PATH_COLLISION = "WORKTREE_PATH_COLLISION"
WORKTREE_NAME_INVALID = "WORKTREE_NAME_INVALID"
WORKTREE_CREATE_PLANNED = "WORKTREE_CREATE_PLANNED"
WORKTREE_CREATE_OK = "WORKTREE_CREATE_OK"
MAIN_CHECKOUT_ALLOWED = "MAIN_CHECKOUT_ALLOWED"

# Legacy reconcile classifications
OBSOLETE_REMOVE = "OBSOLETE_REMOVE"
NEEDED_QUICK_FINISH = "NEEDED_QUICK_FINISH"
NEEDED_FOLLOWUP_ISSUE = "NEEDED_FOLLOWUP_ISSUE"
UNCLEAR_HOLD = "UNCLEAR_HOLD"

LEGACY_CLASSES = frozenset(
    {
        OBSOLETE_REMOVE,
        NEEDED_QUICK_FINISH,
        NEEDED_FOLLOWUP_ISSUE,
        UNCLEAR_HOLD,
    }
)

ENV_WORKTREE_ROOT = "CDB_WORKTREE_ROOT"
DEFAULT_WINDOWS_ROOT = r"Y:\Worktrees"
