"""Constants and reason codes for environment preflight (#4255)."""

from __future__ import annotations

VERDICT_READY_OFFLINE_ONLY = "READY_OFFLINE_ONLY"
VERDICT_READY_FOR_RECORDED_TEST = "READY_FOR_RECORDED_TEST"
VERDICT_BLOCKED = "BLOCKED"
VERDICT_UNAVAILABLE = "UNAVAILABLE"
VERDICT_UNKNOWN = "UNKNOWN"

VERDICTS = frozenset(
    {
        VERDICT_READY_OFFLINE_ONLY,
        VERDICT_READY_FOR_RECORDED_TEST,
        VERDICT_BLOCKED,
        VERDICT_UNAVAILABLE,
        VERDICT_UNKNOWN,
    }
)

CLOUD_AGENT_REQUIRED_FIELDS = (
    "profile_version",
    "allowed_provider_ids",
    "provider_config_ref",
    "provider_config_digest_policy",
    "source_commit_binding",
    "workspace_policy",
    "allowed_paths",
    "forbidden_paths",
    "allowed_command_classes",
    "required_toolchain",
    "setup_policy",
    "network_policy",
    "secret_policy",
    "resource_limits",
    "execution_limits",
    "cost_limit",
    "artifact_policy",
    "checkpoint_policy",
    "required_attestations",
    "live_dispatch_allowed",
)

GOVERNED_PROFILE_IDS = (
    "cdb-docs-readonly.v1",
    "cdb-agent-skills.v1",
    "cdb-python-fast.v1",
    "cdb-ci-debug.v1",
    "cdb-validation-research.v1",
    "cdb-runtime-risk-restricted.v1",
)

PROVIDER_CONFIG_REF_DEFAULT = ".cursor/environment.json"

# Durable live-dispatch gate (not temporary "#4255" wording).
ENVIRONMENT_LIVE_DISPATCH_FORBIDDEN = "ENVIRONMENT_LIVE_DISPATCH_FORBIDDEN"
PROVIDER_LIVE_DISPATCH_FORBIDDEN = "PROVIDER_LIVE_DISPATCH_FORBIDDEN"

REASON_SETUP_FAILED = "ENVIRONMENT_SETUP_FAILED"
REASON_SETUP_UNPROVEN = "ENVIRONMENT_SETUP_UNPROVEN"
REASON_FALLBACK_FORBIDDEN = "ENVIRONMENT_FALLBACK_FORBIDDEN"
REASON_FALLBACK_UNPROVEN = "ENVIRONMENT_FALLBACK_UNPROVEN"
REASON_PROFILE_DIGEST_MISMATCH = "ENVIRONMENT_PROFILE_DIGEST_MISMATCH"
REASON_CONFIG_MISSING = "ENVIRONMENT_CONFIG_MISSING"
REASON_CONFIG_SCHEMA_INVALID = "ENVIRONMENT_CONFIG_SCHEMA_INVALID"
REASON_SOURCE_COMMIT_MISMATCH = "ENVIRONMENT_SOURCE_COMMIT_MISMATCH"
REASON_BASE_IDENTITY_UNVERIFIED = "ENVIRONMENT_BASE_IDENTITY_UNVERIFIED"
REASON_REQUIRED_TOOL_MISSING = "ENVIRONMENT_REQUIRED_TOOL_MISSING"
REASON_TOOL_VERSION_MISMATCH = "ENVIRONMENT_TOOL_VERSION_MISMATCH"
REASON_WORKSPACE_SCOPE_INVALID = "ENVIRONMENT_WORKSPACE_SCOPE_INVALID"
REASON_EGRESS_UNENFORCED = "ENVIRONMENT_EGRESS_UNENFORCED"
REASON_SECRET_SCOPE_VIOLATION = "ENVIRONMENT_SECRET_SCOPE_VIOLATION"
REASON_RESOURCE_LIMIT_UNVERIFIED = "ENVIRONMENT_RESOURCE_LIMIT_UNVERIFIED"
REASON_COST_LIMIT_UNVERIFIED = "ENVIRONMENT_COST_LIMIT_UNVERIFIED"
REASON_ARTIFACT_PATH_INVALID = "ENVIRONMENT_ARTIFACT_PATH_INVALID"
REASON_CHECKPOINT_DRIFT = "ENVIRONMENT_CHECKPOINT_DRIFT"
REASON_ATTENUATION_EMPTY = "ENVIRONMENT_ATTENUATION_EMPTY"
REASON_PROFILE_INCOMPLETE = "ENVIRONMENT_PROFILE_INCOMPLETE"
REASON_PROFILE_UNKNOWN = "ENVIRONMENT_PROFILE_UNKNOWN"
REASON_RUNTIME_BLOCKED = "ENVIRONMENT_RUNTIME_BLOCKED"
REASON_LIVE_DISPATCH = "ENVIRONMENT_LIVE_DISPATCH_FORBIDDEN"
REASON_PROVIDER_NOT_ALLOWED = "ENVIRONMENT_PROVIDER_NOT_ALLOWED"
REASON_PATH_ESCAPE = "ENVIRONMENT_WORKSPACE_SCOPE_INVALID"
REASON_TIMEOUT_CANCEL_UNCONFIRMED = "ENVIRONMENT_TIMEOUT_CANCEL_UNCONFIRMED"
